### ISSUE TITLE
No safe clear cache function

### ISSUE THREAD

**Issue by tugtugtug** [anderslanglands/ustr#18] opened 2021-06-07 15:05 UTC
This lib fits our use case well, except that there is no safe clear function. Is there any reason we could not have a safe clear cache function?

**Comment by anderslanglands** [comment] 2021-06-07 19:32
Hi there! The reason there’s no safe clear_cache is because all `Ustr`s are conceptually a `&’static str` by design. That is, they are assumed to live forever and this design choice makes it easy to store them in structs etc without worrying about lifetimes, making the use of the library much more ergonomic. 

Having a `clear_cache()` function would invalidate this, and require setting up some kind of lifetime tracking to make sure `Ustr`s don’t outlive the “phase” of the cache that they were created in, which again would break the ergonomics. 

You can of course just `unsafe { clear_cache() }` yourself if you are SURE that you are not still using any previously created `Ustr`s, but that responsibility lies with the caller, hence the unsafe.

**Comment by tugtugtug** [comment] 2021-06-07 19:34
got it, thanks @anderslanglands! that makes total sense, and I was just seeking some confirmation if that clear_cache can be ever used if the caller knows that all references are no longer there.

**Comment by anderslanglands** [comment] 2021-06-07 19:41
You’re welcome! Closing this now.

**Closed by anderslanglands** 2021-06-07 19:41 UTC
